name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: dashboard-backend-202503061144  # Your GCP Project ID
  SERVICE_NAME: dashboard-api                 # Cloud Run service name
  REGION: us-central1                         # Cloud Run region

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/217033309165/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@dashboard-backend-202503061144.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push container
        run: |
          docker buildx build --platform linux/amd64 -t $REGION-docker.pkg.dev/$PROJECT_ID/dashboard-repo/dashboard-backend:${{ github.sha }} . --push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/dashboard-repo/dashboard-backend:${{ github.sha }} \
            --region $REGION \
            --project $PROJECT_ID \
            --platform managed \
            --set-env-vars="FRONTEND_URL=https://app.syntheticteams.com,MANDRILL_API_KEY=md-2HbTGMACxIX4m9NlonorzA,FIREBASE_PROJECT_ID=dashboard-55056,GOOGLE_APPLICATION_CREDENTIALS=/secrets/firebase-credentials,FIREBASE_SERVICE_ACCOUNT=/secrets/firebase-credentials,MANDRILL_FROM_EMAIL=ron@syntheticteams.com,MANDRILL_FROM_NAME=Synthetic Teams" \
            --set-secrets="/secrets/firebase-credentials=firebase-credentials:latest" 