name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

env:
  PROJECT_ID: dashboard-backend-202503061144  # Your GCP Project ID
  SERVICE_NAME: dashboard-api                 # Cloud Run service name
  REGION: us-central1                         # Cloud Run region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify dependencies
        run: |
          gcloud --version
          docker --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push container
        run: |
          echo "Building and pushing container image..."
          docker buildx build --platform linux/amd64 -t $REGION-docker.pkg.dev/$PROJECT_ID/dashboard-repo/dashboard-backend:${{ github.sha }} . --push
          echo "Image pushed successfully!"

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          # First, remove the existing environment variable
          gcloud run services update $SERVICE_NAME \
            --region $REGION \
            --project $PROJECT_ID \
            --remove-env-vars="MANDRILL_API_KEY" \
            || echo "No environment variable to remove, continuing..."
          
          # Now deploy with the updated configuration
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/dashboard-repo/dashboard-backend:${{ github.sha }} \
            --region $REGION \
            --project $PROJECT_ID \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars="FRONTEND_URL=https://app.syntheticteams.com" \
            --set-secrets="MANDRILL_API_KEY=mandrill-api-key:latest,/secrets/firebase-credentials=firebase-credentials:latest"

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --platform managed --region $REGION --format 'value(status.url)')
          echo "Service URL: $SERVICE_URL"
          curl -s "$SERVICE_URL/health" | grep -q "ok" && echo "Deployment successful! Health check passed." || echo "Deployment may have issues. Health check failed." 